#!/bin/sh

./cgen/commonapi_core_generator/commonapi-core-generator-linux-x86_64 -sk ./fidl/minesweeper.fidl
./cgen/commonapi_dbus_generator/commonapi-dbus-generator-linux-x86_64 ./fidl/minesweeper.fidl
